version: '3'
services:
  refrig:
    build:
      context: .
#    image: simidot/refrig:latest
    container_name: refrig
    environment:
      - SPRING_PROFILES_ACTIVE=DEV
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD","curl", "-f", "http://localhost:8080/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - refrig_networks
  nginx:
    image: simidot/nginx:latest
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      refrig:
        condition: service_healthy
    volumes:
      # 호스트의 인증서 디렉터리를 읽기 전용으로 마운트
      - /home/ec2-user/certs/fullchain.pem:/etc/letsencrypt/live/myrefrig.site/fullchain.pem:ro
      - /home/ec2-user/certs/privkey.pem:/etc/letsencrypt/live/myrefrig.site/privkey.pem:ro
      # Nginx 설정 파일도 마운트할 수 있음
      - /home/ec2-user/nginx/myrefrig.site.conf:/etc/nginx/conf.d/myrefrig.site.conf:ro
    networks:
      - refrig_networks

networks:
  refrig_networks: