server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  port: 8080
spring:
  profiles:
    active: DEV
  application:
    name: refrig
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

#  mvc:
#    static-path-pattern: /static/**
#    pathmatch:
#      matching-strategy: ant_path_matcher
#  servlet:
#    multipart:
#      max-file-size: 100MB
#      max-request-size: 100MB

springdoc:
  packages-to-scan: com.example.refrig
#  paths-to-match=/**:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    #    path: /
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs

#logging:
#  level:
#    com.zaxxer.hikari: DEBUG